/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatbotRule = IDL.Record({
  'id' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'response' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Helpline = IDL.Record({
  'name' : IDL.Text,
  'number' : IDL.Text,
  'category' : IDL.Text,
});
export const IncidentReport = IDL.Record({
  'id' : IDL.Int,
  'status' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
  'incidentType' : IDL.Text,
});
export const Law = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'resourceType' : IDL.Text,
  'location' : IDL.Text,
});
export const Story = IDL.Record({
  'id' : IDL.Int,
  'isApproved' : IDL.Bool,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addIncidentReport' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addOrUpdateChatbotRule' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addOrUpdateFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addOrUpdateHelpline' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addOrUpdateLaw' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addOrUpdateQuizQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addOrUpdateResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addStory' : IDL.Func([IDL.Text], [], []),
  'approveStory' : IDL.Func([IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChatbotRule' : IDL.Func([IDL.Text], [], []),
  'deleteFAQ' : IDL.Func([IDL.Text], [], []),
  'deleteHelpline' : IDL.Func([IDL.Text], [], []),
  'deleteLaw' : IDL.Func([IDL.Text], [], []),
  'deleteQuizQuestion' : IDL.Func([IDL.Text], [], []),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'deleteStory' : IDL.Func([IDL.Int], [], []),
  'getAllChatbotRules' : IDL.Func([], [IDL.Vec(ChatbotRule)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllHelplines' : IDL.Func([], [IDL.Vec(Helpline)], ['query']),
  'getAllIncidentReports' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllLaws' : IDL.Func([], [IDL.Vec(Law)], ['query']),
  'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getApprovedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIncidentStatus' : IDL.Func([IDL.Int, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatbotRule = IDL.Record({
    'id' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'response' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Helpline = IDL.Record({
    'name' : IDL.Text,
    'number' : IDL.Text,
    'category' : IDL.Text,
  });
  const IncidentReport = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
    'incidentType' : IDL.Text,
  });
  const Law = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'resourceType' : IDL.Text,
    'location' : IDL.Text,
  });
  const Story = IDL.Record({
    'id' : IDL.Int,
    'isApproved' : IDL.Bool,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addIncidentReport' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addOrUpdateChatbotRule' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addOrUpdateFAQ' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addOrUpdateHelpline' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addOrUpdateLaw' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addOrUpdateQuizQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addOrUpdateResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addStory' : IDL.Func([IDL.Text], [], []),
    'approveStory' : IDL.Func([IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChatbotRule' : IDL.Func([IDL.Text], [], []),
    'deleteFAQ' : IDL.Func([IDL.Text], [], []),
    'deleteHelpline' : IDL.Func([IDL.Text], [], []),
    'deleteLaw' : IDL.Func([IDL.Text], [], []),
    'deleteQuizQuestion' : IDL.Func([IDL.Text], [], []),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'deleteStory' : IDL.Func([IDL.Int], [], []),
    'getAllChatbotRules' : IDL.Func([], [IDL.Vec(ChatbotRule)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllHelplines' : IDL.Func([], [IDL.Vec(Helpline)], ['query']),
    'getAllIncidentReports' : IDL.Func(
        [],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getAllLaws' : IDL.Func([], [IDL.Vec(Law)], ['query']),
    'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getApprovedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIncidentStatus' : IDL.Func([IDL.Int, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };