/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatbotRule {
  'id' : string,
  'keywords' : Array<string>,
  'response' : string,
}
export interface FAQ {
  'id' : string,
  'question' : string,
  'answer' : string,
  'category' : string,
}
export interface Feedback {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Helpline {
  'name' : string,
  'number' : string,
  'category' : string,
}
export interface IncidentReport {
  'id' : bigint,
  'status' : string,
  'description' : string,
  'timestamp' : bigint,
  'location' : string,
  'incidentType' : string,
}
export interface Law {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface QuizQuestion {
  'id' : string,
  'question' : string,
  'correctIndex' : bigint,
  'explanation' : string,
  'options' : Array<string>,
}
export interface Resource {
  'id' : string,
  'contact' : string,
  'name' : string,
  'description' : string,
  'resourceType' : string,
  'location' : string,
}
export interface Story {
  'id' : bigint,
  'isApproved' : boolean,
  'content' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeedback' : ActorMethod<[string, string, string], undefined>,
  'addIncidentReport' : ActorMethod<[string, string, string], undefined>,
  'addOrUpdateChatbotRule' : ActorMethod<
    [string, Array<string>, string],
    undefined
  >,
  'addOrUpdateFAQ' : ActorMethod<[string, string, string, string], undefined>,
  'addOrUpdateHelpline' : ActorMethod<[string, string, string], undefined>,
  'addOrUpdateLaw' : ActorMethod<[string, string, string], undefined>,
  'addOrUpdateQuizQuestion' : ActorMethod<
    [string, string, Array<string>, bigint, string],
    undefined
  >,
  'addOrUpdateResource' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'addStory' : ActorMethod<[string], undefined>,
  'approveStory' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChatbotRule' : ActorMethod<[string], undefined>,
  'deleteFAQ' : ActorMethod<[string], undefined>,
  'deleteHelpline' : ActorMethod<[string], undefined>,
  'deleteLaw' : ActorMethod<[string], undefined>,
  'deleteQuizQuestion' : ActorMethod<[string], undefined>,
  'deleteResource' : ActorMethod<[string], undefined>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'getAllChatbotRules' : ActorMethod<[], Array<ChatbotRule>>,
  'getAllFAQs' : ActorMethod<[], Array<FAQ>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllHelplines' : ActorMethod<[], Array<Helpline>>,
  'getAllIncidentReports' : ActorMethod<[], Array<IncidentReport>>,
  'getAllLaws' : ActorMethod<[], Array<Law>>,
  'getAllQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getApprovedStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIncidentStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];